# Use a lightweight Debian base image
FROM debian:latest

# Install required packages
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    gfortran \
    cmake \
    sqlite3- \
    libsqlite3-dev \
    mpich \
    python3 \
    && rm -rf /var/lib/apt/lists/*

# Set up MPI environment variables
ENV PATH="/usr/lib/x86_64-linux-gnu/mpich/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu/mpich/lib:${LD_LIBRARY_PATH}"

# Set working directory
WORKDIR /workspace


CMD ["/bin/sh"]
