#+title: Software Testing
#+BIBLIOGRAPHY: bibliography plain

* Introduction
** The Software Under Test
The SUT for this assignment is *mpisee*, a profiling tool for MPI applications written in C. The motivation for *mpisee* was to explore the use of MPI communicators. This was not possible with other state-of-the-art profiling tools since they disregard communicators. Originally, I have developed this tool for personal use but we decided that it can be published since it is a useful tool and a new idea. We published *mpisee* in the [[https://hips2022.github.io/][IPDPS 2022 HIPS workshop]].

** Testing the software
*mpisee* is a new (less than 9 months) software and it's a work in progress, this means that some MPI calls are not supported, and it has not been tested thoroughly. Also, I am the only developer of mpisee it is tricky to be the tester, since I am biased. Therefore, I was thrilled when this guest lecture on Software Testing was offered. Testing mpisee presents a lot of challenges since it is a parallel program, although it is not as complicated as Object-oriented code it still poses many challenges.
*** Challenges
First, because it is a profiler, the input of mpisee can be any MPI application and these MPI applications have, additionally, different inputs on their own. This creates an infinite space of possible inputs for mpisee. Second, the profiler should be able to handle any number of processes or at least be aware of the maximum number of processes it can handle. Third, parallelism and the dependence on MPI library add another layer of complexity to testing such software.
Besides the challenges due to the nature of MPI, parallelism and profiling I had to deal with other more technical issues. Some of the technical issues was to learn how to compile with CMake and use Ctest to automate the testing process. In other words, create an infrastructure that would automate the way to add new tests and run them.
*** Methods
I have chosen to create Metamorphic Tests along with some basic functional and correctness tests since the input space is too large to be handled otherwise. I was glad to explore and create such tests and I was not aware of Metamorphic testing before discussing it in this course. Writing tests for mpisee is easier when being the developer of the software and knowing exactly its structure. Additionally, the simple code structure of mpisee allowed me to expose the necessary structures that were required for testing. More details on the actual testing are provided in the corresponding section.

* Infrastructure
* Testing
** Setting the infrastructure
** Metamorphic relations
- Call Bcast (or any rooted) with different root but with the same buffer size
- Think of more metamorphic relations
* Conclusion
* Bibliography
#+BEGIN_SRC latex
\bibliographystyle{plain}
\bibliography{biblio}
#+END_SRC
